### ISSUE TITLE
kawaii mascot for  anime not found error :)

### ISSUE THREAD

**Issue by Cosmicoppai** [Cosmicoppai/LiSA#10]

**Comment by NishantChaware** [comment]
Attach image required @Cosmicoppai

**Comment by Cosmicoppai** [comment]
![toppng.com-cute-anime-girl-stickers-messages-sticker-8-anime-girl-sticker-transparent-321x290.png](https://user-images.githubusercontent.com/63765823/186966082-fce5421d-d807-4baa-83ff-1f00216ea5c3.png)
