### ISSUE TITLE
npm run build:package:windows after running thia it shows resource folder is not their

### ISSUE THREAD

**Issue by rakeshsarkar9711** [Cosmicoppai/LiSA#43]

**Comment by Cosmicoppai** [comment]
Hi @rakeshsarkar9711 Do you want to build from source or your just testing out the app?

You can download the app from [LiSA](https://github.com/Cosmicoppai/LiSA/releases/download/v1.0.0/LiSA-win32-x64.zip).

If you want to build it from the code, you can check https://github.com/Cosmicoppai/LiSA#building-from-source

Make sure you are installing all the python dependencies prior running the build command.

**Comment by Cosmicoppai** [comment]
@rakeshsarkar9711 Make sure you're in the virtual env.

Also, It would be great if you can provide ```pip freeze``` output :)

**Comment by rakeshsarkar9711** [comment]
after this when i open the application the application pages stays blank

**Comment by Cosmicoppai** [comment]
@rakeshsarkar9711

Can you provide the output of ```pip freeze``` and provide some SS or logs of build, cuz I'm unable to reproduce it.

Make sure to include python & node version along with system specs.

**Comment by rakeshsarkar9711** [comment]
aiobotocore==2.5.4
aiohttp==3.8.5
aioitertools==0.11.0
aiosignal==1.3.1
altgraph==0.17.4
anyio==3.7.1
async-timeout==4.0.3
attrs==23.1.0
beautifulsoup4==4.12.2
boto3==1.28.17
botocore==1.31.17
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
colorama==0.4.6
exceptiongroup==1.1.3
frozenlist==1.4.0
fsspec==2023.6.0
h11==0.14.0
idna==3.4
iso8601==2.0.0
jmespath==1.0.1
m3u8==3.5.0
multidict==6.0.4
pathvalidate==3.1.0
pefile==2023.2.7
progress==1.6
pyathena==3.0.6
pycryptodome==3.18.0
pyinstaller==5.6.1
pyinstaller-hooks-contrib==2023.8
python-dateutil==2.8.2
pywin32-ctypes==0.2.2
s3fs==2023.6.0
s3transfer==0.6.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
starlette==0.31.0
tenacity==8.2.3
typing_extensions==4.7.1
urllib3==1.26.16
uvicorn==0.23.2
websockets==11.0.3
wrapt==1.15.0
yarl==1.9.2


py = 3.11.5
node = 30.7.0

**Comment by rakeshsarkar9711** [comment]
Host Name:                 CODEZERO
OS Name:                   Microsoft Windows 11 Home Single Language
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          rakeshsarkar9711@outlook.com
Registered Organization:   N/A
Product ID:                00356-24591-91075-AAOEM
Original Install Date:     8/29/2023, 11:19:08 AM
System Boot Time:          9/27/2023, 12:39:45 AM
System Manufacturer:       LENOVO
System Model:              82NL
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 165 Stepping 2 GenuineIntel ~2496 Mhz
BIOS Version:              LENOVO G8CN23WW, 6/7/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
Total Physical Memory:     8,100 MB
Available Physical Memory: 2,121 MB
Virtual Memory: Max Size:  17,828 MB
Virtual Memory: Available: 7,470 MB
Virtual Memory: In Use:    10,358 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\CODEZERO
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5029921
                           [02]: KB5030310
                           [03]: KB5028756
                           [04]: KB5030508
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.2
                                 [02]: fe80::1435:1ea7:152:f714
                           [02]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by Cosmicoppai** [comment]
The issue, #44, has been resolved. You can try building the project after pulling the latest changes.

Please note that the watchList and Manga Integration features are still under development. 
However, you are welcome to use the other available features :)

**Comment by hemanth-kumar-boddeda** [comment]
HI @Cosmicoppai why no anime is been ready to watch?

**Comment by Cosmicoppai** [comment]
@hemanth-kumar-boddeda 
It's been a while, we are no longer actively maintaining this repo.
The Site scraper might have broken because of the following reasons:

Site schema changes.
Crawler Blocked due to some reason.


Let's hope, someday we'll able to get some time from our schedule to maintain this project.

In the meantime, Please feel free to dig into issue 😉.

**Comment by Cosmicoppai** [comment]
@hemanth-kumar-boddeda Linking the crawler code: https://github.com/Cosmicoppai/LiSA/blob/main/backend/scraper/scraper.py
