### ISSUE TITLE
i am getting white screen 

### ISSUE THREAD

**Issue by saimahendra282** [Cosmicoppai/LiSA#50]
![image](https://github.com/Cosmicoppai/LiSA/assets/118994059/6d2277c4-ebf6-477f-8cb0-f120e17df0bb)
hello there,
i executed your project step by step,but i am getting this screen would you mind helping me out??

**Comment by Cosmicoppai** [comment]
@saimahendra282 can you please paste all commands that you used.
Btw the scraper is broken at the moment
