### ISSUE TITLE
stable version

### ISSUE THREAD

**Issue by FruitsAndVegetables** [Cosmicoppai/LiSA#62]
Error with the stable version link. I tried LiSA v1.1.0, but the search function can't find any anime, and when I pick an anime, it keeps buffering.

**Comment by Cosmicoppai** [comment]
Hi @FruitsAndVegetables, the issue will be fixed in the next release on 20-07-2024.
In the meanwhile, you can use the dev branch the setup is fairly quick and simple.

**Comment by Cosmicoppai** [comment]
https://github.com/Cosmicoppai/LiSA/releases/tag/v2.0.0-beta
