### ISSUE TITLE
"LiSA.app" is damaged and can't be opened.

### ISSUE THREAD

**Issue by QasimXAli** [Cosmicoppai/LiSA#64]
Downloaded the latest beta for Mac but it says "LiSA.app" is damaged and can't be opened. You should move it to the Bin. Tried downloading it twice but same error. Running on M1 Macbook air.

**Comment by mrakesh0608** [comment]
@QasimXAli, please run this command after installing.

```
xattr -c /Applications/LiSA.app
```

**Comment by QasimXAli** [comment]
Perfect. Thank you soo much
